language: ruby
rvm:
  - 2.2.4
  - 2.3.1
  - 2.4.1

before:
  - git show-ref | grep $(git log --pretty=%h -1) | sed 's|.*/\(.*\)|\1|' | sort -u | grep -v HEAD
  - git show -s --pretty=%d HEAD
  - git for-each-ref --format='%(objectname) %(refname:short)' refs/heads | awk "/^$(git rev-parse HEAD)/ {print \$2}"
  - git show -s --pretty=%D HEAD | tr -s ', ' '\n' | grep -v HEAD | head -n1
  - git name-rev --name-only HEAD
