name: Release gem

on:
  repository_dispatch:
    types:
      - release-patch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - name: Install gems
      run: |
        gem install bundler -v 2.0.2
        bundle install
    - name: configure git
      run: |
        git config user.email "beth@bethesque.com"
        git config user.name "Beth Skurrie via Github Actions"
    - name: "script"
      run: script/prepare-release.sh
      env:
        INCREMENT: patch
    - name: Release Gem
      uses: cadwallion/publish-rubygems-action@v1.0.0
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_API_KEY}}
