name: Trigger release of the pact-cli Docker image
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GHTOKENFORPACTCLIRELEASE }}
          repository: pact-foundation/pact-ruby-cli
          event-type: gem-released
